### ISSUE TITLE
SBE tool 1.35 throws java.lang.IllegalAccessError with Java 23 on MacOS

### ISSUE THREAD

**Issue by marvin-hansen** [real-logic/simple-binary-encoding#1039]
Hi, 

I've tried to upgrade from SBE 1.30 to 1.35 and while doing so I encountered an IllegalAccessError.

When running: 

```Bash
$ java  -Dsbe.generate.ir=true -Dsbe.target.language=Rust -Dsbe.target.namespace=sbe  -jar sbe-all-${SBE_LIB_VERSION}.jar schema.xml
```

With SBE 1.30 , the command completes. 

With SBE 1.35, however, I get the following error: 

```Bash
Exception in thread "main" java.lang.IllegalAccessError: class org.agrona.UnsafeApi (in unnamed module @0x234bef66) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @0x234bef66
	at org.agrona.UnsafeApi.getUnsafe(UnsafeApi.java)
	at org.agrona.UnsafeApi.<clinit>(UnsafeApi.java)
	at org.agrona.BufferUtil.<clinit>(BufferUtil.java:43)
	at org.agrona.concurrent.UnsafeBuffer.wrap(UnsafeBuffer.java:176)
	at org.agrona.concurrent.UnsafeBuffer.<init>(UnsafeBuffer.java:91)
	at uk.co.real_logic.sbe.ir.IrEncoder.<init>(IrEncoder.java:55)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:311)
make: *** [sbe] Error 1
```

Please advise. 

Thank you,

System: 

```Bash
uname -a
Darwin MacBook-Pro.local 24.2.0 Darwin Kernel Version 24.2.0:

java --version
openjdk 23.0.1 2024-10-15
OpenJDK Runtime Environment Homebrew (build 23.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 23.0.1, mixed mode, sharing)
```

**Comment by marvin-hansen** [comment]
The exact same error is thrown with the official JDK 17 from Oracle.

```
java --version
java 17.0.12 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 17.0.12+8-LTS-286)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.12+8-LTS-286, mixed mode, sharing)
```

**Comment by marvin-hansen** [comment]
Is there any Java flag that needs to be set?

**Comment by marvin-hansen** [comment]
Okay, after looking at the Gradle build file, I found the missing flag:

`java --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dsbe.xinclude.aware=true  ... `

Did the trick. 

Would be possible to mention that workaround in the Readme?

**Comment by vyazelenko** [comment]
@marvin-hansen The release notes for the latest release [1.34.0](https://github.com/real-logic/simple-binary-encoding/releases/tag/1.34.0) contain breaking changes section which mentions the `--add-opens java.base/jdk.internal.misc=ALL-UNNAMED` JVM option.
I'll update README file as well.
