### ISSUE TITLE
RC3 <data> in repeating group?

### ISSUE THREAD

**Issue by andmer** [real-logic/simple-binary-encoding#301]
Hi All,

I'm testing SBE, and I added variable length string data type to perf/resources/sbe/fix-message-samples.xml but am getting the following generating codecs.

        <composite name="varDataEncoding">
            <type name="length" primitiveType="uint8" />
            <type name="varData" primitiveType="uint8" length="0" characterEncoding="UTF-8" />
        </composite>

    <message name="MarketDataIncrementalRefreshTrades" id="2" semanticType="X" description="Trade">
        <field name="TransactTime" id="60" type="timestamp" timeUnit="nanossecond"/>
        <field name="EventTimeDelta" id="37704" type="uint16"/>
        <field name="MatchEventIndicator" id="5799" type="MatchEventIndicator"/>
        <group name="MdIncGrp" id="268">
           <data name="MDEntryID" id="278" type="varDataEncoding" />
            <field name="TradeId" id="1003" type="uint64"/>
            <field name="SecurityId" id="48" type="uint64"/>
            <field name="MdEntryPx" id="270" type="Decimal64"/>
            <field name="MdEntrySize" id="271" type="IntQty32"/>
            <field name="NumberOfOrders" id="346" type="uint16"/>
            <field name="MdUpdateAction" id="279" type="MDUpdateAction"/>
            <field name="RptSeq" id="83" type="uint8"/>
            <field name="AggressorSide" id="5797" type="Side"/>
            <field name="MdEntryType" id="269" type="MDEntryType" constant="2"/>
        </group>
    </message>

ERROR: at <message name="MarketDataIncrementalRefreshTrades"> <group name="MdIncGrp"> field node specified after group or data node specified
Exception in thread "main" java.lang.IllegalArgumentException: at <message name="MarketDataIncrementalRefreshTrades"> <group name="MdIncGrp"> field node specified after group or data node specified
	at uk.co.real_logic.sbe.xml.ErrorHandler.error(ErrorHandler.java:73)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.handleError(XmlSchemaParser.java:221)
	at uk.co.real_logic.sbe.xml.Message.parseFieldsAndGroups(Message.java:187)
	at uk.co.real_logic.sbe.xml.Message.parseGroupField(Message.java:232)
	at uk.co.real_logic.sbe.xml.Message.parseFieldsAndGroups(Message.java:175)
	at uk.co.real_logic.sbe.xml.Message.<init>(Message.java:76)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser$5.execute(XmlSchemaParser.java:198)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.forEach(XmlSchemaParser.java:396)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.findMessages(XmlSchemaParser.java:193)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:102)
	at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:225)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:149)
:generateExampleCodecs FAILED

**Comment by mjpt777** [comment]
Current version supports RC2. I will be adding RC3 shortly.

**Comment by andmer** [comment]
Thanks Martin!
