### ISSUE TITLE
failed to pass java test

### ISSUE THREAD

**Issue by chengm349** [real-logic/simple-binary-encoding#306]
platform:

Linux FLXSGLDV04 3.10.0-229.el7.x86_64 #1 SMP Thu Jan 29 18:37:38 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

Java

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateCharEnumStub FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateRepeatingGroupDecoder FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateBasicMessage FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateReadOnlyMessage FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateUint8EnumStub FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateVarDataCodecs FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateCompositeDecoder FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateMessageHeaderStub FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateMessageHeaderDecoderStub FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateCompositeEncoder FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateBitSetCodecs FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateCompositeDecodings FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateChoiceSetStub FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

uk.co.real_logic.sbe.generation.java.JavaGeneratorTest > shouldGenerateEnumCodecs FAILED
    java.lang.IllegalStateException at JavaGeneratorTest.java:456

106 tests completed, 14 failed

Is it ok?

**Comment by chengm349** [comment]
CMake Error at CMakeLists.txt:73 (message):
  could not find latest SBE jar in
  /fs02/home/mcheng/workspace/Trunk_US/directfeeds/cme/simple-binary-encoding-master/build/libs

Is it because previous java testing failed; so no SBE jar?

**Comment by mjpt777** [comment]
What command did you run to execute the tests? Also can you paste in the failure report for one of the failed tests?

**Comment by chengm349** [comment]
I ran ./gradlew.

Report here:

java.lang.IllegalStateException: JDK required to run tests. JRE is not sufficient.
	at uk.co.real_logic.agrona.generation.CompilerUtil.compileInMemory(CompilerUtil.java:55)
	at uk.co.real_logic.sbe.generation.java.JavaGeneratorTest.compile(JavaGeneratorTest.java:456)
	at uk.co.real_logic.sbe.generation.java.JavaGeneratorTest.compileCarEncoder(JavaGeneratorTest.java:417)
	at uk.co.real_logic.sbe.generation.java.JavaGeneratorTest.shouldGenerateBasicMessage(JavaGeneratorTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

My colleague installed jre. I installed jdk. I thought the system can find jdk.
