### ISSUE TITLE
presence="optional" ?

### ISSUE THREAD

**Issue by andmer** [real-logic/simple-binary-encoding#325]
Sorry not sure the best venue to ask questions of authors but:

How do I determine nullValue from spec if optional field from decoder? is this implemented in Java? trying to figure it out. thanks!

**Comment by tmontgomery** [comment]
Each field should get a nullValue() method that returns the NULL value. Then that can be compared to the actual value from the decoder. All the logic of setting the null value in the encoder is left to the app to do as the spec suggests.

**Comment by andmer** [comment]
Hi Todd, thanks and btw I've enjoyed quite a few of your talks from youtube!

That makes sense. 
Questions still persist though, sorry to say. I'm not exactly sure how to apply that in this case.

I'm trying to model an optional variable length string.

for example:
...snip...
`
        <composite name="varDataEncoding">
            <type name="length" primitiveType="uint8" />
            <type name="varData" primitiveType="uint8" length="0" characterEncoding="UTF-8" />
        </composite>
`
...snip...

`
        <data name="CFICode" id="461" type="varDataEncoding" presence="optional"/>
`
I'm not sure how to get that nullvalue determined from the generated decoder in this case.

I have these generated methods in decoder:
`    

    public static int cFICodeHeaderLength()
    {
        return 1;
    }

    public int cFICodeLength()
    {
        final int limit = parentMessage.limit();
        return (short)(buffer.getByte(limit) & 0xFF);
    }

    public int getCFICode(
        final uk.co.real_logic.agrona.MutableDirectBuffer dst, final int dstOffset, final int length)
    {
        final int sizeOfLengthField = 1;
        final int limit = parentMessage.limit();
        final int dataLength = (short)(buffer.getByte(limit) & 0xFF);
        final int bytesCopied = Math.min(length, dataLength);
        parentMessage.limit(limit + sizeOfLengthField + dataLength);
        buffer.getBytes(limit + sizeOfLengthField, dst, dstOffset, bytesCopied);

        return bytesCopied;
    }

    public int getCFICode(
        final byte[] dst, final int dstOffset, final int length)
    {
        final int sizeOfLengthField = 1;
        final int limit = parentMessage.limit();
        line 2297: final int dataLength = (short)(buffer.getByte(limit) & 0xFF);
        final int bytesCopied = Math.min(length, dataLength);
        parentMessage.limit(limit + sizeOfLengthField + dataLength);
        buffer.getBytes(limit + sizeOfLengthField, dst, dstOffset, bytesCopied);

        return bytesCopied;
    }

    public String cFICode()
    {
        final int sizeOfLengthField = 1;
        final int limit = parentMessage.limit();
        final int dataLength = (short)(buffer.getByte(limit) & 0xFF);
        parentMessage.limit(limit + sizeOfLengthField + dataLength);
        final byte[] tmp = new byte[dataLength];
        buffer.getBytes(limit + sizeOfLengthField, tmp, 0, dataLength);

        final String value;
        try
        {
            value = new String(tmp, "UTF-8");
        }
        catch (final java.io.UnsupportedEncodingException ex)
        {
            throw new RuntimeException(ex);
        }

        return value;
    }`

here is a sample of the original exception accessing the String field

`

        java.lang.IndexOutOfBoundsException: index=159, length=1, capacity=159
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:1046)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.getByte(UnsafeBuffer.java:761)
	at com.fxcm.messaging.sbe.fix.MarketDataSnapshotFullRefreshDecoder.cFICode(MarketDataSnapshotFullRefreshDecoder.java:2297)
	at com.fxcm.messaging.sbe.codec.MarketDataSnapshotFullRefreshCodec.decode(MarketDataSnapshotFullRefreshCodec.java:88)
	at com.fxcm.messaging.sbe.codec.MarketDataSnapshotFullRefreshCodec.decode(MarketDataSnapshotFullRefreshCodec.java:39)
	at com.fxcm.messaging.ABaseTest.testEquality(ABaseTest.java:130)
	at com.fxcm.messaging.sbe.SBEMarketDataSnapshotTest.testEquality(SBEMarketDataSnapshotTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
`

**Comment by mjpt777** [comment]
Null value on an optional var data field is an empty string. There is no "null" concept in the specification. I asked about this when we first implemented and the feedback I got was null and empty string are the same thing. I don't share this view but we implemented as per the specification.

**Comment by andmer** [comment]
ohh ok so is it my responsibility to encode the nullvalue? it is not derived in the decoder if absent?

**Comment by tmontgomery** [comment]
Glad you liked my talks! :)

What I mentioned was for fields (the fixed size `<field>` elements).

You might want to file a bug against the String Decoder for VarData for that exception. Since I am not entirely sure what is going on there.

But to answer the question on VarData.

The FIX/SBE spec itself doesn't distinguish between VarData that is present, but empty, and VarData not present.

But, VarData can be optional by setting the length to 0 on the "put" method of the Encoder. Then the Decoder can check using the "Length" method or the return value from one of the "get" methods.

Alternatively, the app could use a default value for the VarData field if it needs to distinguish between 0 length, but it exists, and a default value indicating not set at all. For this default, you might want to consider a length of 1 and a special character outside the encoding (for example).

**Comment by tmontgomery** [comment]
It is the applications responsibility to fill VarData. Either make it empty (0 length) or with some data.

**Comment by andmer** [comment]
ahh ok guys. thanks!  I was operating under the wrong assumption.

Martin, your talks are great too, btw.

this all makes sense now.

**Comment by mjpt777** [comment]
@andmer Thanks for the feedback. Please fill a bug on the exception, or I can. We should report the issue more clearly.
