### ISSUE TITLE
Fail to Generate C++ Code?

### ISSUE THREAD

**Issue by structurechart** [real-logic/simple-binary-encoding#352]
I ran:
./gradlew

and

./cppbuild/cppbuil

And then I ran

java -Dsbe.target.language=cpp -jar ~/simple-binary-encoding-1.4.0-RC4/sbe-all/build/libs/sbe-all-1.4.0-RC4.jar templates.xml 
Exception in thread "main" java.lang.IllegalStateException: Invalid property name='final' please correct the schema or consider setting system property: sbe.keyword.append.token
	at uk.co.real_logic.sbe.generation.cpp.CppUtil.formatPropertyName(CppUtil.java:96)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator.lambda$generateChoices$8(CppGenerator.java:651)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator$$Lambda$8/824318946.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator.generateChoices(CppGenerator.java:648)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator.generateChoiceSet(CppGenerator.java:584)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator.generateTypeStubs(CppGenerator.java:82)
	at uk.co.real_logic.sbe.generation.cpp.CppGenerator.generate(CppGenerator.java:118)
	at uk.co.real_logic.sbe.SbeTool.generate(SbeTool.java:254)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:179)

Any idea what's going on?

**Comment by mjpt777** [comment]
Yes. Your input schema has a field of the name "final" and this is a keyword clash.  If you set the following property then it will append a "_" to the name so it no longer clashes.

-Dsbe.keyword.append.token=_

**Comment by mjpt777** [comment]
Or don't use keywords for field names :)
