### ISSUE TITLE
building sbe - gradle certificate issue

### ISSUE THREAD

**Issue by prashn** [real-logic/simple-binary-encoding#431]
I am trying to get around the certificate issue. When I run gradlew I get errors even after adding 
"-Dcom.sun.net.ssl.checkRevocation=false -Dtrust_all_cert=true ". Any ideas how I can bypass it? Thanks.

+ exec java -Dcom.sun.net.ssl.checkRevocation=false -Dtrust_all_cert=true -Dorg.gradle.appname=gradlew -classpath /home/<user>/simple-binary-encoding-1.5.5/gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain
Downloading https://services.gradle.org/distributions/gradle-3.2.1-all.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:273)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1472)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:213)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:913)
....

**Comment by mjpt777** [comment]
We do not use SSL in SBE so you should take this up with the Gradle folks.
