### ISSUE TITLE
IllegalStateException generating IR from CME templates

### ISSUE THREAD

**Issue by tamboril** [real-logic/simple-binary-encoding#469]
With the HEAD at d80ec49, if I try to generate IR from the current CME `templates_FixBinary.xml`,
I get this:
```
 ./generate.sh
Exception in thread "main" java.lang.IllegalStateException: PrimitiveValue is not a long representation
        at uk.co.real_logic.sbe.PrimitiveValue.longValue(PrimitiveValue.java:277)
        at uk.co.real_logic.sbe.ir.IrUtil.put(IrUtil.java:276)
        at uk.co.real_logic.sbe.ir.IrEncoder.encodeToken(IrEncoder.java:181)
        at uk.co.real_logic.sbe.ir.IrEncoder.encodeTokenList(IrEncoder.java:104)
        at java.util.HashMap$Values.forEach(HashMap.java:980)
        at uk.co.real_logic.sbe.ir.IrEncoder.encode(IrEncoder.java:95)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:232)
```
My generate.sh is:
```

SBE_JAR=$HOME/repos/sbe.git/sbe-all/build/libs/sbe-all-1.7.1-SNAPSHOT.jar
SCHEMA=./templates_FixBinary.xml

java\
  -Dsbe.output.dir=codecs\
  -Dsbe.generate.ir="true"\
  -Dsbe.target.language="cpp"\
  -Dsbe.keyword.append.token="true"\
  -Dsbe.target.namespace="mktdata"\
  -jar $SBE_JAR $SCHEMA
```

[templates_FixBinary.zip](https://github.com/real-logic/simple-binary-encoding/files/1091736/templates_FixBinary.zip)

**Comment by mjpt777** [comment]
I've pushed a fix for this. Can you retest please?

**Comment by tamboril** [comment]
Does not crash with commit `56417075`.  Generates `.sbeir` file as expected.

Thanks.

Closing...
