### ISSUE TITLE
RustGeneratorTest > constantFieldsCase FAILED

### ISSUE THREAD

**Issue by mjpt777** [real-logic/simple-binary-encoding#500]
Marking as ignored until fixed.

```
uk.co.real_logic.sbe.generation.rust.RustGeneratorTest > constantFieldsCase FAILED
    java.lang.AssertionError: Did not contain pub struct CompositeWithConst {
      pub w:u8,
    }
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.assertContains(RustGeneratorTest.java:312)
        at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.constantFieldsCase(RustGeneratorTest.java:279)
```

**Comment by mjpt777** [comment]
When this tests fails then the following two test have assumption failures as knock on effects.

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>


	at org.junit.Assume.assumeThat(Assume.java:95)
	at org.junit.Assume.assumeTrue(Assume.java:41)
	at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.assertRustBuildable(RustGeneratorTest.java:227)
	at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.fullGenerateBroadUseCase(RustGeneratorTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

```
org.junit.AssumptionViolatedException: got: <false>, expected: is <true>


	at org.junit.Assume.assumeThat(Assume.java:95)
	at org.junit.Assume.assumeTrue(Assume.java:41)
	at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.assertRustBuildable(RustGeneratorTest.java:227)
	at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.assertSchemaInterpretableAsRust(RustGeneratorTest.java:236)
	at uk.co.real_logic.sbe.generation.rust.RustGeneratorTest.checkValidRustFromAllExampleSchema(RustGeneratorTest.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by ZackPierce** [comment]
@mjpt777 
Given the presence of  `JUnit4IdeaTestRunner` in the stack traces, I assume these snippets are pulled from IntelliJ. 

What I'd like to confirm is whether those stack traces are indicative full-on failures, or merely loudly-logged dynamic ignores that IntelliJ is presenting as if they were actual test failures.

A quick way to check would be to remove the `@Ignore`s recently added and run the tests through `./gradlew` and see if the build succeeds. Running the tests with gradle should use the default JUnit test runners, which should correctly report overall success when some individual tests get dynamically ignored due to assumption-checking.  IMHO, the gradle build should probably be the source of truth for build success, and we should strive to avoid permanently ignoring tests that could be conditionally ignored only when necessary.

Sadly, I lack an accessible Windows box to run this check myself in a timely manner.

**Comment by ZackPierce** [comment]
Separately, I'm feeling confident that headlining issue about not finding a given text snippet in the generated code is a matter of platform-specific handling of newline characters, which should be readily resolvable.

**Comment by mjpt777** [comment]
I've tested both in the IDE and on the command line and get the same warnings and errors.
