### ISSUE TITLE
Getting started guide would be nice

### ISSUE THREAD

**Issue by Markvy** [real-logic/simple-binary-encoding#508]
Maybe the "target audience" for this thing is people not as clueless as me, but... I can't get this to work.
I've tried two things so far:

`java -jar sbe-all-1.7.1.jar sbe-samples-1.7.1\example-schema.xml`
no effect

`java -cp sbe-benchmarks-1.7.1;sbe-all-1.7.1 uk.co.real_logic.sbe.CarBenchmark`
This one did have an effect, just not a nice one:
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: uk/co/real_logic/sbe/benchmarks/MessageHeaderEncoder
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: uk.co.real_logic.sbe.benchmarks.MessageHeaderEncoder
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more`
I'm clearly doing something wrong.

**Comment by Markvy** [comment]
Maybe here?
https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/java/overview.html

**Comment by Markvy** [comment]
Okay, so maybe never mind.  It DOES have an effect.  It creates a folder "baseline" which I totally overlooked.  Sorry.
