### ISSUE TITLE
`make test` in gocode directory fails

### ISSUE THREAD

**Issue by maciej** [real-logic/simple-binary-encoding#532]
As in the issue title, `make test` fails with:

```
⨯ make test                                                                                                                          10:46:17
(cd ..; gradlew generateGolangCodecs)
/bin/sh: gradlew: command not found
make: *** [src/simple/SbeMarshalling.go] Error 127
```

when fixing the issue of `gradlew` not being available (prepending the command with `./`) I get the following:

```
◦ make test                                                                                                                          11:07:49
(cd ..; ./gradlew generateGolangCodecs)

> Task :generateGolangCodecsWithXSD FAILED
Exception in thread "main" java.lang.IllegalStateException: type is not of constant presence
        at uk.co.real_logic.sbe.xml.EncodedDataType.constVal(EncodedDataType.java:295)
        at uk.co.real_logic.sbe.xml.IrGenerator.add(IrGenerator.java:461)
        at uk.co.real_logic.sbe.xml.IrGenerator.addAllFields(IrGenerator.java:181)
        at uk.co.real_logic.sbe.xml.IrGenerator.generateForMessage(IrGenerator.java:83)
        at uk.co.real_logic.sbe.xml.IrGenerator.generate(IrGenerator.java:59)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:199)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGolangCodecsWithXSD'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
8 actionable tasks: 5 executed, 3 up-to-date
make: *** [src/simple/SbeMarshalling.go] Error 1
```

I'm using the current `master` branch, Java 1.8_144, Go 1.9 and recent MacOS.

**Comment by billsegall** [comment]
This is being triggered by the test case for [issue 483](https://github.com/real-logic/simple-binary-encoding/issues/483). The failing test case is [issue483.xml](https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/test/resources/issue483.xml).

Any known recent changes around presence="constant" that may have triggered this?

**Comment by mjpt777** [comment]
@billsegall could this change have effected it? https://github.com/real-logic/simple-binary-encoding/commit/a699b4cbc3b62528f7cafba1f9e84a809d54d57c
