### ISSUE TITLE
messageHeader fields type

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#628]
Hello devs!

My `messageHeader` definition looks like:
```xml
    <composite name="messageHeader" description="Message identifiers and length of message root">                                                              
        <type name="blockLength" primitiveType="uint8"/>                                                                                                       
        <type name="templateId" primitiveType="uint8"/>                                                                                                        
        <type name="schemaId" primitiveType="uint8"/>                                                                                                          
        <type name="version" primitiveType="uint8"/>                                                                                                           
    </composite> 
```

But `sbe-tool` print errors during generation:
```bash
> java -Dsbe.xinclude.aware=true -Dsbe.target.language=cpp -jar sbe-all-1.11.0.jar market-data.xml
WARNING: at <sbe:message name="Snapshot_15"> <group name="NoMDEntries"> "blockLength" should be UINT8 or UINT16
WARNING: at <sbe:message name="Snapshot_15"> <group name="NoMDEntries"> "numInGroup" should be UINT8 or UINT16
WARNING: at <#document><messageSchema>"blockLength" should be UINT16
ERROR: at <#document><messageSchema>"templateId" must be UINT16
ERROR: at <#document><messageSchema>"schemaId" must be UINT16
ERROR: at <#document><messageSchema>"version" must be UINT16
Exception in thread "main" java.lang.IllegalStateException: had 3 errors
        at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit(ErrorHandler.java:105)
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:131)
        at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:286)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:205)
```
Is types for `templateId`, `schemaId`, `version` required to be UINT16 by specification? Or it restriction of `sbe-tool`?

Thanks

**Comment by mjpt777** [comment]
This is the recommendation of the standard.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-STANDARD/doc/03MessageStructure.md#message-header-schema

In addition, if the message does not start 8 byte aligned then aligning fields is difficult for the message definitions.

**Comment by ksergey** [comment]
@mjpt777 So is this possible to print warning instead of throw exception?

**Comment by mjpt777** [comment]
Standard OTF will not work then if someone takes this approach.

**Comment by ksergey** [comment]
But why blockLength type is modifiable? Also the same for group size encoding types.

**Comment by mjpt777** [comment]
There are some issues with the standard which I do not agree with but they are what they are. I think these things should be fixed to allow for more certainty when moving between schemas, plus OTF can be optimised and Wireshark disectors are possible. This all feels like flexibility for flexibility sake and yet raises more issues than it solves ;-)

**Comment by ksergey** [comment]
Ok :)
