### ISSUE TITLE
[C++] GeneratedStubExample throws exception

### ISSUE THREAD

**Issue by ksergey** [real-logic/simple-binary-encoding#722]
Hello Devs!

Binary `GeneratedStubExample` throws `std::runtime_error` during execution.

```
> ./binaries/GeneratedStubExample
Encoded Lengths are 8 + 201
terminate called after throwing an instance of 'std::runtime_error'
  what():  unknown value for enum BooleanType [E103]
Aborted (core dumped)
```

Backtrace:
```
(gdb) bt
#0  0x00007f507ab2d755 in raise () from /usr/lib/libc.so.6
#1  0x00007f507ab18851 in abort () from /usr/lib/libc.so.6
#2  0x00007f507aeab81f in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f507aeb830a in __cxxabiv1::__terminate (handler=<optimized out>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f507aeb72da in __cxa_call_terminate (ue_header=ue_header@entry=0x55a9c4a182e0)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00007f507aeb7ca5 in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=6, exception_class=5138137972254386944,
    ue_header=0x55a9c4a182e0, context=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_personality.cc:677
#6  0x00007f507acc66d3 in _Unwind_RaiseException_Phase2 (exc=0x55a9c4a182e0, context=0x7ffc54e5c710, frames_p=0x7ffc54e5c800)
    at /build/gcc/src/gcc/libgcc/unwind.inc:64
#7  0x00007f507acc6c22 in _Unwind_RaiseException (exc=exc@entry=0x55a9c4a182e0) at /build/gcc/src/gcc/libgcc/unwind.inc:136
#8  0x00007f507aeb85ae in __cxxabiv1::__cxa_throw (obj=<optimized out>,
    tinfo=0x55a9c3229d80 <typeinfo for std::runtime_error@@GLIBCXX_3.4>, dest=0x7f507aece7e0 <std::runtime_error::~runtime_error()>)
    at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:90
#9  0x000055a9c3220a70 in baseline::BooleanType::get (value=229 '\345')
    at /home/ksergey/dev/simple-binary-encoding/debug/generated/cpp/baseline/BooleanType.h:110
#10 0x000055a9c322138b in baseline::Engine::boosterEnabled (this=0x7ffc54e5ca90)
    at /home/ksergey/dev/simple-binary-encoding/debug/generated/cpp/baseline/Engine.h:779
#11 0x000055a9c322463a in baseline::operator<< <char, std::char_traits<char> > (builder=..., writer=...)
    at /home/ksergey/dev/simple-binary-encoding/debug/generated/cpp/baseline/Engine.h:865
#12 0x000055a9c3224027 in baseline::operator<< <char, std::char_traits<char> > (builder=..., _writer=...)
    at /home/ksergey/dev/simple-binary-encoding/debug/generated/cpp/baseline/Car.h:2583
#13 0x000055a9c321fb2c in main (argc=1, argv=0x7ffc54e5d8a8)
    at /home/ksergey/dev/simple-binary-encoding/sbe-samples/src/main/cpp/GeneratedStubExample.cpp:312
```

**Comment by tmontgomery** [comment]
Head of the repo works fine for me on MacOS. What platform, compiler, etc. are you using?

**Comment by ksergey** [comment]
@tmontgomery 

Platform:: linux (archlinux)
Compiler: GCC 9.1.0

Steps:
[![asciicast](https://asciinema.org/a/tRJKFOpHHInIUwtBVoFkfTeSp.svg)](https://asciinema.org/a/tRJKFOpHHInIUwtBVoFkfTeSp)

**Comment by tmontgomery** [comment]
I don't see it terminating. But I do see that the generated JSON from 54291b696b8eacf31d8b6c3c2dcecb4846fb6bf5 is triggering valgrind. That is not showing up when the generated JSON is not used in the example. So, I suspect that the generated pretty printer is causing it.

**Comment by ksergey** [comment]
@tmontgomery Yes, this fix the issue.

**Comment by tmontgomery** [comment]
Yeah, it's the pretty print logic. Somewhere it is messing up something. I'll have to look into it. As it is something we don't use, not top of the list.

**Comment by dxwu88** [comment]
CME iLink3 will use SBE for order routing. Are you going to implement the encoding for it? Thanks!

On Sep 17, 2019, at 4:39 PM, Todd L. Montgomery <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, it's the pretty print logic. Somewhere it is messing up something. I'll have to look into it. As it is something we don't use, not top of the list.

**Comment by tmontgomery** [comment]
We have nothing to do with the CMEs usage of SBE.

**Comment by tmontgomery** [comment]
Actually, the GeneratedStubExample did not set new fields in the schema added after the example was written. I've changed that. Now it runs valgrind clean with JSON pretty printing from commit f8e3255acdd9b9893e27f0fdc9a888d457e6f883
