### ISSUE TITLE
Using the sbe with Eurex templates

### ISSUE THREAD

**Issue by matigurten** [real-logic/simple-binary-encoding#808]
I am trying to use the sbeTool with the Eurex codecs which can be found in the Eurex site (file eobi81.xml)

https://www.eurexchange.com/exchange-en/technology/t7/release81

JAVA -Dsbe.target.namespace=eobiV81 -classpath  "../sbe-tool-1.7.0.jar;../agrona-0.9.6.jar" uk.co.real_logic.sbe.SbeTool eobi81.xml 

This eobi.xml file looks slightly different from the sample provided and the tool execution fails (it succeeds on the the car.xml example file):

Exception in thread "main" java.lang.NullPointerException
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.getAttributeValue(XmlSchemaParser.java:221)
        at uk.co.real_logic.sbe.xml.MessageSchema.<init>(MessageSchema.java:47)
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:105)
        at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:274)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:199)

Can anyone help me find a way to get the xml compiling? I believe maybe the eobi.xsd file should be useful, but not sure how.

Thanks

**Comment by tmontgomery** [comment]
You should add both `sbe.validation.xsd` and `sbe.validation.stop.on.error` to your command. Also, the XSD to use is the standard based one. It is located at:

https://github.com/real-logic/simple-binary-encoding/blob/master/sbe-tool/src/main/resources/fpl/sbe.xsd

Using another XSD is not standard.

**Comment by mjpt777** [comment]
@matigurten Please test with the latest SBE and Agrona. The version you are using is very old.

**Comment by matigurten** [comment]
Ok, I upgraded the jars and now I am doing 

JAVA -Dsbe.target.namespace=eobiV81 -Dsbe.validation.stop.on.error=true -Dsbe.validation.xsd=../sbe.xsd -classpath  "../sbe-tool-1.19.0.jar;../agrona-1.6.0.jar" uk.co.real_logic.sbe.SbeTool eobi81.xml 

And I am still getting the same message:

[Error] eobi81.xml:2:416: cvc-elt.1: Cannot find the declaration of element 'ns2:Model'.
Exception in thread "main" java.lang.NullPointerException
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.getAttributeValue(XmlSchemaParser.java:282)
        at uk.co.real_logic.sbe.xml.MessageSchema.<init>(MessageSchema.java:50)
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:149)
        at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:308)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:215)


Attached is the file I am trying to parse

Thanks!

**Comment by ksergey** [comment]
Eurex don't uses SBE.

**Comment by matigurten** [comment]
But it is a similar format, with fixed length and repeating groups...

I believe the template can be "translated" to be sbe compliant, but if done manually it looks like an insane amount of work.

Does anyone have an Idea on how to generate the stubs from this kind of schema?

Thanks

**Comment by mjpt777** [comment]
This schema is not valid SBE. This implementation only works for 1.0 final version of SBE.
