### ISSUE TITLE
I can't use common-types.xml (Exception)

### ISSUE THREAD

**Issue by chtrading** [real-logic/simple-binary-encoding#809]
I am trying to use the common-types.xml but this is happening:
```
[ch@localhost resources]$ java -jar ~/sbe/simple-binary-encoding/sbe-all/build/libs/sbe-all-1.19.1-SNAPSHOT.jar common-types.xml 
Exception in thread "main" java.lang.NullPointerException
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.getAttributeValue(XmlSchemaParser.java:277)
	at uk.co.real_logic.sbe.xml.MessageSchema.<init>(MessageSchema.java:50)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:144)
	at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:308)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:215)
[ch@localhost resources]$ 
```
I have another .xml from Exchange and it is working, but the common-types.xml (together with example-schema.xml) is more simple and I think that it can be useful for learning purpose.

**Comment by mjpt777** [comment]
Pass `example-schema.xml` as an argument and it will include `common-types.xml`. You can follow the examples to see how this is done as part of the build.

**Comment by chtrading** [comment]
> Pass example-schema.xml as an argument

Yes, but the result was:
```
[ch@localhost simple-binary-encoding]$ java -jar ~/sbe/simple-binary-encoding/sbe-all/build/libs/sbe-all-1.19.1-SNAPSHOT.jar ~/sbe/simple-binary-encoding/sbe-samples/src/main/resources/example-schema.xml
ERROR: at <sbe:message name="Car"> <group name="fuelFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="fuelFigures"> <data name="usageDescription"> could not find type: varAsciiEncoding
ERROR: at <sbe:message name="Car"> <group name="performanceFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="performanceFigures"> <group name="acceleration"> could not find dimensionType: groupSizeEncoding
ERROR: at <sbe:message name="Car"> <data name="manufacturer"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="model"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="activationCode"> could not find type: varAsciiEncoding
Exception in thread "main" java.lang.IllegalStateException: had 7 errors
	at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit(ErrorHandler.java:105)
	at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:141)
	at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:308)
	at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:215)
[ch@localhost simple-binary-encoding]$ 

```

Probably because he couldn't find the other xml

> You can follow the examples 

I did this grep:
```
[ch@localhost simple-binary-encoding]$ grep -r -n -e "example-schema.xml" ./*
./build/sbe-samples/src/main/cpp/CMakeFiles/examples_codecs.dir/build.make:76:generated/cpp/baseline: ../sbe-samples/src/main/resources/example-schema.xml
./build/sbe-samples/src/main/cpp/CMakeFiles/examples_codecs.dir/build.make:79:	cd /home/ch/sbe/simple-binary-encoding/build/sbe-samples/src/main/cpp && /usr/bin/java -Dsbe.output.dir=/home/ch/sbe/simple-binary-encoding/build/generated/cpp -Dsbe.generate.ir=true -Dsbe.target.language=cpp -Dsbe.xinclude.aware=true -jar /home/ch/sbe/simple-binary-encoding/sbe-all/build/libs/sbe-all-1.19.1-SNAPSHOT.jar /home/ch/sbe/simple-binary-encoding/sbe-samples/src/main/resources/example-schema.xml
grep: ./build/core.26161: Permission denied
./build.gradle:388:        args = ['src/main/resources/example-schema.xml', 'src/main/resources/example-extension-schema.xml']
./build.gradle:564:    args = ['sbe-samples/src/main/resources/example-schema.xml',
./build.gradle:613:    args = ['sbe-samples/src/main/resources/example-schema.xml',
./cppbuild/build/sbe-samples/src/main/cpp/CMakeFiles/examples_codecs.dir/build.make:76:generated/cpp/baseline: ../../sbe-samples/src/main/resources/example-schema.xml
./cppbuild/build/sbe-samples/src/main/cpp/CMakeFiles/examples_codecs.dir/build.make:79:	cd /home/ch/sbe/simple-binary-encoding/cppbuild/build/sbe-samples/src/main/cpp && /usr/bin/java -Dsbe.output.dir=/home/ch/sbe/simple-binary-encoding/cppbuild/build/generated/cpp -Dsbe.generate.ir=true -Dsbe.target.language=cpp -Dsbe.xinclude.aware=true -jar /home/ch/sbe/simple-binary-encoding/sbe-all/build/libs/sbe-all-1.19.1-SNAPSHOT.jar /home/ch/sbe/simple-binary-encoding/sbe-samples/src/main/resources/example-schema.xml
./csharp/sbe-samples-car/sbe-samples-car.csproj:11:    <Content Include="..\..\sbe-samples\src\main\resources\example-schema.xml" Link="example-schema.xml" />
./gocode/src/example-schema/CarExample.go:1:// golang example code for SBE's example-schema.xml
./sbe-samples/src/main/cpp/CMakeLists.txt:22:set(EXAMPLES_SCHEMA ${CODEC_EXAMPLES_SCHEMA_DIR}/example-schema.xml)
Binary file ./sbe-samples/build/libs/sbe-samples-1.19.1-SNAPSHOT.jar matches
```
**So I noticed the option -Dsbe.xinclude.aware=true**

Now it is working:

```
[ch@localhost simple-binary-encoding]$ java -Dsbe.xinclude.aware=true -jar ~/sbe/simple-binary-encoding/sbe-all/build/libs/sbe-all-1.19.1-SNAPSHOT.jar ~/sbe/simple-binary-encoding/sbe-samples/src/main/resources/example-schema.xml
[ch@localhost simple-binary-encoding]$ 

```
