### ISSUE TITLE
Example schemas not working

### ISSUE THREAD

**Issue by yadamit** [real-logic/simple-binary-encoding#929]
I am trying to run example schemas as per wiki given in `./simple-binary-encoding/sbe-samples/src/main/resources/example-schema.xml` but I am getting this error:
```
$ java -Dsbe.target.language=CPP -jar ./simple-binary-encoding/sbe-all/build/libs/sbe-all-1.27.1-SNAPSHOT.jar ./simple-binary-encoding/sbe-samples/src/main/resources/example-schema.xml
ERROR: at <sbe:message name="Car"> <group name="fuelFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="fuelFigures"> <data name="usageDescription"> could not find type: varAsciiEncoding
ERROR: at <sbe:message name="Car"> <group name="performanceFigures"> could not find dimensionType: groupSizeEncoding
ERROR: at <group name="performanceFigures"> <group name="acceleration"> could not find dimensionType: groupSizeEncoding
ERROR: at <sbe:message name="Car"> <data name="manufacturer"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="model"> could not find type: varStringEncoding
ERROR: at <sbe:message name="Car"> <data name="activationCode"> could not find type: varAsciiEncoding
Exception in thread "main" java.lang.IllegalStateException: had 7 errors
        at uk.co.real_logic.sbe.xml.ErrorHandler.checkIfShouldExit(ErrorHandler.java:107)
        at uk.co.real_logic.sbe.xml.XmlSchemaParser.parse(XmlSchemaParser.java:141)
        at uk.co.real_logic.sbe.SbeTool.parseSchema(SbeTool.java:331)
        at uk.co.real_logic.sbe.SbeTool.main(SbeTool.java:232)
```

Is it because the schemas are no longer valid? I am using this java version:
```
$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```
I am kinda new to this. Any help is much appreciated.

**Comment by yadamit** [comment]
Go it working by including `-Dsbe.xinclude.aware=true` flag as mentioned in #809 .
